# Generated by Django 5.0.3 on 2024-03-26 09:59

import ckeditor_uploader.fields
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shwet_Multimetal_Company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='This is a product', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=30, unique=True),
        ),
    ]
