# Generated by Django 5.0.3 on 2024-04-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shwet_Multimetal_Company', '0018_remove_product_id_alter_category_cid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pid',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cid',
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
