# Generated by Django 5.0.3 on 2024-04-13 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shwet_Multimetal_Company', '0019_rename_pid_product_id_remove_category_cid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
