# Generated by Django 5.0.3 on 2024-04-13 10:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shwet_Multimetal_Company', '0021_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default=uuid.uuid4, max_length=30, unique=True),
        ),
    ]
