# Generated by Django 5.0.3 on 2024-04-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shwet_Multimetal_Company', '0023_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
