# Generated by Django 5.0.3 on 2024-04-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shwet_Multimetal_Company', '0030_rename_timestamp_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(default="(0, '☆☆☆☆☆')", max_length=10),
        ),
    ]
