# Generated by Django 5.0.3 on 2024-04-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shwet_Multimetal_Company', '0035_product_color_product_grade_product_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
