# Generated by Django 5.0.3 on 2024-04-17 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shwet_Multimetal_Company', '0036_remove_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='timeStamp',
            new_name='timestamp',
        ),
    ]
