# Generated by Django 5.0.3 on 2024-04-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shwet_Multimetal_Company', '0037_rename_timestamp_contact_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
